config/routes.rb
Rails.application.routes.draw do
  root to: 'topics#index'
  resources :topics, only: [:show], param: :name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/snapshot.rb
class Snapshot < ApplicationRecord
  validates :active_user_count, :subscribers, presence: true

  belongs_to :topic

  def activity_ratio
    active_user_count * 1.0 / subscribers
  end

end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :name, presence: true

  has_many :snapshots

  def subreddit_name
    "/r/#{name}"
  end

  def subreddit_url
    "https://www.reddit.com/r/#{name}"
  end

  def delta_hour
    delta.try(:[], 'hour')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    topic = Topic.find_by(name: params[:name])
    @chart_data = Topics::ChartData.new(topic)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
  def percentage(decimal, params={precision: 2})
    number_to_percentage(decimal * 100, params)
  end

  def positive_negative_color_class(number)
    return if number.nil?
    if number > 0
      'text-success'
    elsif number < 0
      'text-danger'
    end
  end

  def delta_indicator(delta)
    color = delta >= 0 ? 'delta-positive' : 'delta-negative'
    content_tag :small, class: "delta-indicator #{color}" do
      number_to_percentage delta*100, precision: 0
    end
  end

end

app/views/application/_analytics.html.haml
- if Rails.env.production?
  -# gtag manager (Google Analytics)
  %script{src: "https://www.googletagmanager.com/gtag/js?id=UA-111474828-1", async: true}
  :javascript
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    $(document).on('turbolinks:load', function() {
      gtag('config', 'UA-111474828-1', {'page_path': window.location.pathname});
    });

app/views/application/_sidebar.html.haml
.col-md-3.sidebar
  %nav.sidebar-nav
    .sidebar-header
      = link_to root_url, class: 'sidebar-brand' do
        %h2
          kiss
          %span.text-muted> trends

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title KissTrends
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'analytics'

  %body
    .container
      .row
        = render 'sidebar'
        .col-md-9.content
          = yield

app/views/topics/index.html.haml
.dashhead
  .dashhead-titles
    %h6.dashhead-subtitle Subreddits
    %h2.dashhead-title Most Active

.table
  %table.table{data: { sort: 'table' }}
    %thead
      %tr
        %th.header /r/
        %th.header Active Users
        %th.header Subscribers
        %th.header Activity Ratio
        %th.header Delta (hour)
        %th.header Details
    %tbody
      - @topics.each do |topic|
        %tr
          %td= link_to topic.name, topic.subreddit_url
          %td= number_with_delimiter topic.active_user_count
          %td= number_with_delimiter topic.subscribers
          %td= percentage topic.activity_ratio
          %td{class: positive_negative_color_class(topic.delta_hour)}
            - if topic.delta_hour.present?
              = percentage topic.delta_hour, precision: 0
          %td= link_to "View", topic_path(topic.name)

app/views/topics/show.html.haml
.dashhead
  .dashhead-titles
    %h6.dashhead-subtitle Subreddits
    %h2.dashhead-title= @chart_data.subreddit_name

.row.statcards
  .col-md-6.col-xl-3.mb-3.mb-md-4.mb-xl-0
    .statcard.statcard-success
      .p-3
        %span.statcard-desc Active Users
        %h2.statcard-number
          = number_to_human @chart_data.active_user_count.value
  .col-md-6.col-xl-3.mb-3.mb-md-4.mb-xl-0
    .statcard.statcard-danger
      .p-3
        %span.statcard-desc Subscribers
        %h2.statcard-number
          = number_to_human @chart_data.subscribers.value
  .col-md-6.col-xl-3.mb-3.mb-md-4.mb-xl-0
    .statcard.statcard-info
      .p-3
        %span.statcard-desc Activity Ratio
        %h2.statcard-number
          = percentage @chart_data.activity_ratio.value
          = delta_indicator @chart_data.activity_ratio.delta

.row.mt-5
  .col-md-12
    %canvas#historical-chart{data: {points: @chart_data.data.to_s.html_safe, labels: @chart_data.labels.to_s.html_safe}}